"""Initialize database

Revision ID: 23fe2b0af284
Revises: 27f981a2ac73
Create Date: 2023-07-29 18:19:19.707253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fe2b0af284'
down_revision = '27f981a2ac73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
