"""Add date stamp to the `bookmarked_recipes` table

Revision ID: 3e2eb516ce69
Revises: ff74b94b24e2
Create Date: 2023-07-25 18:46:28.701906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2eb516ce69'
down_revision = 'ff74b94b24e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarked_recipes', sa.Column('date_added', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarked_recipes', 'date_added')
    # ### end Alembic commands ###
